<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<AssemblyName>FullPotential.Models</AssemblyName>
	</PropertyGroup>

	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<Copy SourceFiles="$(TargetPath)" DestinationFolder="D:\Dev\FullPotential\FullPotential\Assets\Plugins\FullPotential\" />
	</Target>
	
</Project>
